### ISSUE TITLE
Access to Floating Topics

### ISSUE THREAD

**Issue by artshcherbina** [xmindltd/xmind-sdk-python#20]
Hello!

Thank you for your project.
Currently, I can't find interface to Floating Topics in the XMind. 

Best regards,
Artem

**Comment by cohenjo** [comment]
Hi,
You can get them by sending an additional parameter to the "topic.getSubTopics()" call passing "detached" as a parameter.
for example:
`for topic in root_topic.getSubTopics(const.TOPIC_DETACHED) or []:`

I've sent a pull request to add a constant to `const.py`
#22 

Regards,
- Jony

**Comment by artshcherbina** [comment]
Thank you very much, it works!

Best regards,
Artem
